name: @name@
main: com.github.unchama.seichiassist.SeichiAssist
version: @version@

commands:
  gacha:
    permission: multiseichiplugin.seichi
    permission-message: You don't have <permission>
  seichihaste:
    permission: multiseichiplugin.seichihaste
    permission-message: You don't have <permission>
  seichiassist:
    permission: multiseichiplugin.seichiassist
    permission-message: You don't have <permission>
  openpocket:
    permission: multiseichiplugin.openpocket
    permission-message: You don't have <permission>
  ef:
    permission: multiseichiplugin.ef
    permission-message: You don't have <permission>
  lastquit:
    permission: multiseichiplugin.lastquit
    permission-message: You don't have <permission>
  rmp:
    permission: multiseichiplugin.rmp
    permission-message: You don't have <permission>
  stick:
    permission: multiseichiplugin.stick
    permission-message: You don't have <permission>
  shareinv:
    default-permission: NOT_OP
    permission-message: You don't have <permission>
  mebius:
    default-permission: NOT_OP
    permission-message: You don't have <permission>
  achievement:
    usage: /<command> <操作> <実績No> <スコープ指定子>
    permission: multiseichiplugin.achievement
    permission-message: You don't have <permission>
  halfguard:
    permission: multiseichiplugin.halfguard
    permission-message: You don't have <permission>
  event:
    permission: multiseichiplugin.event
    default-permission: OP
  contribute:
    permission: multiseichiplugin.contribute
    permission-message: You don't have <permission>
  subhome:
    permission: multiseichiplugin.subhome
    permission-message: You don't have <permission>
  gtfever:
    permission: multiseichiplugin.gtfever
    permission-message: You don't have <permission>
  minehead:
    permission: multiseichiplugin.minehead
    permission-message: You don't have <permission>
  x-transfer:
    usage: /<command> [region name] [new owner name]
    permission: multiseichiplugin.x-transfer
    permission-message: You don't have <permission>
  fly:
    description: This is a fly command.
    usage: /<command> <finish/amount/endless>
    permission-message: You don't have <permission>
    permission: multibuildplugin.build